<!DOCTYPE html>
<html lang="en">
<head>

	<?php // Title generated by Wordpress ?>

    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="referrer" content="always"/>
    <link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
    <link href="<?php echo THEME_IMAGES; ?>/favicon.png" rel="icon" type="image/x-icon">

	<?php wp_head(); ?>

</head>

<body <?php body_class(); ?>>

<?php // Site tracking scripts
get_template_part( 'template-parts/tracking/analytics' ) ?>

<div id="main-container" class="site-wrapper">

	<?php // Content: Header
	if ( class_exists( 'WooCommerce' ) ) {

		get_template_part( 'template-parts/header/header-shop' );

	} else {

		get_template_part( 'template-parts/header/header-main' );

	} ?>

    <div class="<?php echo is_front_page() ? 'home' : 'page' ?>-content site-content">